title: 'A Palm Beach Regency Estate - Offered for $12,950,000 USD'
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5625
  brandStrength: 0.6875
  rhythmicContrast: 0.9347897863481194
  brandColors:
    - '#ffffff'
    - '#182f58'
    - '#9c6f38'
    - '#2b89c6'
    - '#c09c65'
  lightness: 0.5
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: 500RegentsPark
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.8187184
layout_spectrum: 1
