name: 500RegentsPark
favicon: null
layout_spectrum: 0.2990452947560698
typography_spectrum: 0.4500476960092783
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#182f58'
    - '#9c6f38'
    - '#2b89c6'
    - '#c09c65'
  brandStrength: 0.6875
  lightness: 0.5
  saturation: 0.5625
  rhythmicContrast: 0.9347897863481194
purpose: []
